# 跳过构建在Commit Message中添加 [CI SKIP]
kind: pipeline
name: 打包部署[NodeJs-Npm]

clone:
  disable: true

steps:
  - name: 下载源代码[Git]
    image: docker:git
    commands:
      - echo "### $DRONE_GIT_HTTP_URL -> $DRONE_BRANCH"
      - git clone $DRONE_GIT_HTTP_URL ./
      - git checkout $DRONE_BRANCH

  - name: 编译源代码[Npm]
    image: node:10.15.2-alpine
    volumes:
      - name: package-nodejs
        path: /package-nodejs
    commands:
      - npm config set unsafe-perm true
      - npm config set cache "/package-nodejs/npm-cache"
      - npm config set prefix "/package-nodejs/npm"
      - npm config set registry https://registry.npm.taobao.org --global
      - npm config set disturl https://npm.taobao.org/dist --global
      - npm install --prefer-offline
      - npm run build-proxy
      - mv dist/ server/
      - cd server
      - npm install --prefer-offline

  - name: 构建镜像[Docker]
    image: plugins/docker
    settings:
      registry: '172.16.29.104:8850'
      repo: '172.16.29.104:8850/nodejs-service/clever-quartz-ui-server'
      # bip: true
      insecure: true
      dockerfile: ./Dockerfile
      target: dev
      tags: ['0.0.1-SNAPSHOT']
      force_tag: true
      auto_tag: false
      auto_tag_suffix: ''

  - name: 启动容器[SSH-Docker]
    image: appleboy/drone-ssh
    settings:
      host: 172.17.0.1
      port: 22
      username:
        from_secret: SshUsername
      password:
        from_secret: SshPassword
      command_timeout: 300
      script:
        - echo "------------------< 停止容器 >------------------"
        - docker stop clever-quartz-ui-server
        - echo "------------------< 删除容器 >------------------"
        - docker rm -v clever-quartz-ui-server
        - echo "------------------< 删除旧镜像 >------------------"
        - docker rmi 172.16.29.104:8850/nodejs-service/clever-quartz-ui-server:0.0.1-SNAPSHOT
        - echo "------------------< 拉取新镜像 >------------------"
        - docker pull 172.16.29.104:8850/nodejs-service/clever-quartz-ui-server:0.0.1-SNAPSHOT
        - echo "------------------< 运行新镜像 >------------------"
        - docker run --name clever-quartz-ui-server -d -p 8883:8883 172.16.29.104:8850/nodejs-service/clever-quartz-ui-server:0.0.1-SNAPSHOT
        - exit

  - name: 发送通知[Email]
    image: drillster/drone-email
    # detach: true
    settings:
      host: smtp.163.com
      port: 465
      username:
        from_secret: EmailUsername
      password:
        from_secret: EmailPassword
      skip_verify: true
      from:
        from_secret: EmailUsername
      recipients: [ 'lzw1000000@163.com' ]
      recipients_only: true
      subject: '[#{{build.number}}-{{build.status}}] {{repo.name}}'
      body: 'file:///drone/src/drone-email.html'

volumes:
  # nodejs打包目录
  - name: package-nodejs
    host:
      path: /opt/package/nodejs

# -------------------------------------------------------------------------------------------------------------
